<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Open the Webpage]]>
    </line>
    <line>
      <![CDATA[verified title]]>
    </line>
    <line>
      <![CDATA[Close the browser]]>
    </line>
  </reporter-output>
  <suite started-at="2024-05-24T20:22:28 IST" name="Default Suite" finished-at="2024-05-24T20:22:41 IST" duration-ms="12228">
    <groups>
    </groups>
    <test started-at="2024-05-24T20:22:28 IST" name="FST_TestNG" finished-at="2024-05-24T20:22:41 IST" duration-ms="12228">
      <class name="Activities.Activity1">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:Activities.Activity1@12d4bf7e]" started-at="2024-05-24T20:22:28 IST" name="SetUp" finished-at="2024-05-24T20:22:39 IST" duration-ms="10654" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Open the Webpage]]>
            </line>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="task2()[pri:0, instance:Activities.Activity1@12d4bf7e]" started-at="2024-05-24T20:22:39 IST" name="task2" finished-at="2024-05-24T20:22:39 IST" duration-ms="111" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [expected] but found [Black]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [expected] but found [Black]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Activities.Activity1.task2(Activity1.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- task2 -->
        <test-method signature="task4()[pri:0, instance:Activities.Activity1@12d4bf7e]" started-at="2024-05-24T20:22:39 IST" name="task4" finished-at="2024-05-24T20:22:39 IST" duration-ms="0" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[This test case is skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: This test case is skipped
at Activities.Activity1.task4(Activity1.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- task4 -->
        <test-method signature="tasks()[pri:0, instance:Activities.Activity1@12d4bf7e]" started-at="2024-05-24T20:22:39 IST" name="tasks" finished-at="2024-05-24T20:22:39 IST" duration-ms="19" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[verified title]]>
            </line>
          </reporter-output>
        </test-method> <!-- tasks -->
        <test-method is-config="true" signature="Clean()[pri:0, instance:Activities.Activity1@12d4bf7e]" started-at="2024-05-24T20:22:39 IST" name="Clean" finished-at="2024-05-24T20:22:41 IST" duration-ms="1304" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Close the browser]]>
            </line>
          </reporter-output>
        </test-method> <!-- Clean -->
      </class> <!-- Activities.Activity1 -->
    </test> <!-- FST_TestNG -->
  </suite> <!-- Default Suite -->
</testng-results>
